name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              
  build-and-deploy:
    needs: code-analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    env:
      IMAGE_NAME: kamal201999/hello-kubernetes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Pull and Deploy
        run: |
          docker pull $IMAGE_NAME:${{ github.sha }}
          echo "Docker image ready for Kubernetes deployment"

  IAC:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure SSH Keys from Secrets
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "KEY_NAME=deployer-${{ github.run_id }}" >> $GITHUB_ENV
              
      - name: Terraform Init
        run: terraform -chdir=Terraform init

      - name: Terraform Validate
        run: terraform -chdir=Terraform validate

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "Running terraform apply..."
          terraform -chdir=Terraform apply -auto-approve \
           -var="key_name=${{ env.KEY_NAME }}" \
           -var="public_key=${{ env.PUBLIC_KEY }}" \
           -var="private_key=${{ env.PRIVATE_KEY }}"

          ec2_ip=$(terraform -chdir=Terraform output -raw ec2_public_ip | tr -d '\n' | tr -d '\r')
          echo "$ec2_ip" > ec2_ip.txt
          echo "-----SUCCESSFULLY COMPLETED CREATION-----"

      - name: Upload EC2 IP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ec2-ip
          path: ec2_ip.txt

  kubernetes:
    needs: IAC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download EC2 IP Artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-ip

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Validate and Test SSH Key
        run: |
          set -e
          ssh-keygen -l -f ~/.ssh/id_rsa || (echo "INVALID SSH KEY" && exit 1)

          EC2_IP=$(cat ec2_ip.txt | tr -d '\n' | tr -d '\r')
          echo "Resolved EC2 IP: $EC2_IP"
          
          echo "Trying SSH as ubuntu@${EC2_IP}..."
          if ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$EC2_IP "echo connected"; then
            echo "Connected as ubuntu"
            echo "USER=ubuntu" >> $GITHUB_ENV
          else
            echo "Trying SSH as ec2-user@${EC2_IP}..."
            if ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_IP "echo connected"; then
              echo "Connected as ec2-user"
              echo "USER=ec2-user" >> $GITHUB_ENV
            else
              echo "SSH connection failed"
              exit 1
            fi
          fi

      - name: Deploy to Kubernetes
        run: |
          EC2_IP=$(cat ec2_ip.txt | tr -d '\n' | tr -d '\r')
          USER="${{ env.USER }}"

          echo "Copying Kubernetes manifests to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deployment.yaml service.yaml ${USER}@${EC2_IP}:/home/${USER}/

          echo "Starting remote Kubernetes deployment..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${USER}@${EC2_IP} <<EOF
            cd /home/${USER}
            echo "Applying deployment.yaml..."
            kubectl apply -f deployment.yaml

            echo "Applying service.yaml..."
            kubectl apply -f service.yaml

            echo "POD VERIFICATION"
            kubectl get pods -o wide

            echo "SERVICE VERIFICATION"
            kubectl get svc -o wide
EOF

  notify:
    needs: [code-analysis, build-and-deploy, IAC, kubernetes]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "GitHub Actions Pipeline Finished with status: ${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  destroy:
    name: Destroy infra on failure
    if: failure()
    needs: [IAC, kubernetes, notify]
    runs-on: ubuntu-latest
    env: 
      KEY_NAME: deployer-${{ github.run_id }}
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destruction Starts
        run: echo "Some required job failed. Destroying infrastructure due to demo purpose."

      - name: Terraform Init
        run: terraform -chdir=Terraform init

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform -chdir=Terraform destroy -auto-approve -var="key_name=${{ env.KEY_NAME }}"
        
